web:
  build: .
  command: apistar run
  ports:
    - "8080:8080"
  volumes:
    - ./cart_api:/usr/src/app
    - ./cart-frontend:/usr/src/frontend
  links:
    - db

db:
  image: mongo:3.0.2
  ports:
    - "27017:27017"
