web:
  build: .
  command: apistar run
  ports:
    - "8080:8080"
  volumes:
    - ./cart-api:/usr/src/app
    - ./requirements.txt:/usr/src/app/requirements.txt
    - ./cart-frontend:/usr/src/frontend
  links:
    - db
db:
  image: mongo:3.0.2